### ISSUE TITLE
Offline Editor

### ISSUE THREAD

**Issue by ghost** [GrooveProgramming/GrooveProgramming.github.io#2]
I was wondering, does anyone think we could make an offline editor? We could maybe use squeak like Scratch 1.4.

**Comment by ghost** [comment]
I think we should work more on the main version (online) until we have an idea of how it will work and what happens before we do another version in a different language.

We have a small team and I think splitting the project this early on could stall it.

**Comment by ghost** [comment]
> I think we should work more on the main version (online) until we have an idea of how it will work and what happens before we do another version in a different language.
> 
> We have a small team and I think splitting the project this early on could stall it.

Okay, can you work on adding a stage?

**Comment by ghost** [comment]
> I was wondering, does anyone think we could make an offline editor? We could maybe use squeak like Scratch 1.4.

> I think we should work more on the main version (online) until we have an idea of how it will work and what happens before we do another version in a different language.
> 
> We have a small team and I think splitting the project this early on could stall it.

I'm not sure about that right now. We need to get at least most of the online part running because honestly, the offline editor will take more work.

**Comment by ghost** [comment]
> > snip
> 
> Okay, can you work on adding a stage?

Sure. Do you think we should have co-ordinates relative to the camera (like scratch), or have a camera that you can move around (like all game engines I can think of)?

**Comment by ghost** [comment]
> > > snip
> > 
> > 
> > Okay, can you work on adding a stage?
> 
> Sure. Do you think we should have co-ordinates relative to the camera (like scratch), or have a camera that you can move around (like all game engines I can think of)?

I think ones like Scratch.

**Comment by ghost** [comment]
> > > snip
> > 
> > Sure. Do you think we should have co-ordinates relative to the camera (like scratch), or have a camera that you can move around (like all game engines I can think of)?
> 
> I think ones like Scratch.

OK although having a camera is pretty normal for game engines and it is easy to implement, easy to understand (in my opinion), makes scrolling a lot easier and easy to not use.

**Comment by ghost** [comment]
Then let’s use it

**Comment by ghost** [comment]
> > > > snip
> > > 
> > > 
> > > Sure. Do you think we should have co-ordinates relative to the camera (like scratch), or have a camera that you can move around (like all game engines I can think of)?
> > 
> > 
> > I think ones like Scratch.
> 
> OK although having a camera is pretty normal for game engines and it is easy to implement, easy to understand (in my opinion), makes scrolling a lot easier and easy to not use.

Where are you adding it? Almost done?

**Comment by ghost** [comment]
I haven't added it yet as I don't have much time today. 

We also need some sort of interaction with the paint editor to get the costume graphics, and a sprite list / hierarchy thing.

We need a sort of asset storage to store paint files, script data and the like so we can save stuff.

**Comment by ghost** [comment]
> I haven't added it yet as I don't have much time today.
> 
> We also need some sort of interaction with the paint editor to get the costume graphics, and a sprite list / hierarchy thing.
> 
> We need a sort of asset storage to store paint files, script data and the like so we can save stuff.

Ok, can you put the paint editor in the editor for today? Tomorrow, maybe add the stage + other stuff.

**Comment by ghost** [comment]
> > snip
> 
> Ok, can you put the paint editor in the editor for today? Tomorrow, maybe add the stage + other stuff.

Do we not want to do a ~~bit~~ lot more work on the paint editor before it is usable and ready to merge.

**Comment by ghost** [comment]
I'll start doing a stage mock up thing.

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
> Ok

https://jemunm378.github.io/ScratchHelp.github.io/Chat.html Can you meet me here?

**Comment by Mapletron** [comment]
Closed as resolved
