### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by Mapletron** [GrooveProgramming/GrooveProgramming.github.io#7]
Not a necessity, but a night mode would be a nice feature for Groove.

**Comment by jemunm378** [comment]
I got it

**Comment by jemunm378** [comment]
Done

**Comment by jemunm378** [comment]
Hold up, need to add it to all pages

**Comment by Mapletron** [comment]
Wow, that was quite fast.

**Comment by jemunm378** [comment]
Done

**Comment by Mapletron** [comment]
Looks great, closed as resolved.
